// ═══════════════════════════════════════════════════════════════
// PROVENANCE — single source of truth for where every number, quote,
// and claim shown in a memo actually came from.
//
// Traced directly from the generation pipeline (app/api/generate/route.ts,
// lib/prompts/*, lib/categories/shared-prompts.ts, lib/signal-engine/*,
// lib/manufacturing-engine/*) — every classification below reflects what
// the code actually does, not what would be nice to claim.
//
// Four levels, matching how the data is actually produced:
//   verified    — pulled directly from a real external source, no LLM step
//   estimated   — real external data was retrieved AND given to the model
//                 as required grounding context, but the model still wrote
//                 the displayed score/notes text itself (compliance is a
//                 prompt instruction, not a server-enforced override)
//   synthesized — pure model output: pattern-matched from training
//                 knowledge, no external data involved at any stage
//   unknown     — provenance can't be determined (legacy/deprecated
//                 fields, failed-generation placeholders)
// ═══════════════════════════════════════════════════════════════

import type { MemoData, SignalMetadata } from '@/types/index'
import type { AggregatedSignals } from '@/lib/signal-engine/types'
import type { KeywordIntelligence } from '@/lib/keyword-engine/types'
import type { ConsumerIntelligenceReport } from '@/lib/consumer-intelligence'
import type { NewsIntelligence } from '@/lib/news-engine/types'
import type { ScoreDimension } from '@/lib/scoring'
import type { ConsistencyFlag } from '@/lib/consistency'

// 'unsupported' is distinct from legacy 'unknown' — it means a specific,
// checkable claim was compared against real evidence (lib/consistency.ts)
// and contradicted or had no supporting data, not just "provenance unclear."
export type ProvenanceLevel = 'verified' | 'estimated' | 'synthesized' | 'unknown' | 'unsupported'

export interface Provenance {
  level:  ProvenanceLevel
  source: string   // short attribution, e.g. "Keepa (Amazon)"
  detail: string   // one- or two-sentence explanation, used as a tooltip
}

const verified    = (source: string, detail: string): Provenance => ({ level: 'verified', source, detail })
const estimated    = (source: string, detail: string): Provenance => ({ level: 'estimated', source, detail })
const synthesized = (detail: string): Provenance => ({ level: 'synthesized', source: 'Claude (AI synthesis)', detail })
const unsupported = (detail: string): Provenance => ({ level: 'unsupported', source: 'Consistency check', detail })
const unknown      = (detail: string): Provenance => ({ level: 'unknown', source: 'Unclassified', detail })

// ── Fields whose provenance is fixed regardless of which memo you're
// looking at — the generation pipeline never grounds these in real data. ──

export const STATIC_PROVENANCE = {
  executiveSummary: synthesized(
    'Narrative summary written by the model from the category prompt — not fact-checked against any external source.'
  ),
  marketThesis: synthesized(
    'Written in deliberately confident "VC deal memo" voice. Specific-sounding numbers inside this sentence are not independently sourced even when they look precise.'
  ),
  whyNow: synthesized(
    'The model is prompted to cite a concrete-sounding mechanism ("what changed in the last 12–24 months"). That mechanism is plausible pattern completion, not a sourced event — treat any percentage inside this text as unverified unless the Demand Momentum badge below it says otherwise.'
  ),
  buildExplanation: synthesized(
    "Model-written rationale summarizing its own dimension scores — not an independent review of the decision."
  ),
  marketGaps: synthesized(
    "Pattern-matched gaps from the model's training knowledge of the category — not derived from a live competitive scan or review-mining pipeline."
  ),
  brandOpportunities: synthesized(
    'Positioning angles generated by the model as creative suggestions — not tested messaging or validated against real ad performance.'
  ),
  customerLanguage: synthesized(
    'Frustrations, desires, fears, and ad phrases are still model-written, not pulled directly from review text. As of 2026-06-25 the model IS given real Consumer Intelligence themes (when available) and instructed to use them over inventing different ones — see the Consumer tab for the actual real-data themes this should be drawing from. Compliance is a prompt instruction, not server-enforced, so treat this section as informed-by-real-data rather than verified.'
  ),
  productFormula: synthesized(
    "Ingredient choices, doses, and evidence-tier stars are the model's clinical-literature pattern matching — treat as a starting hypothesis, not a citation-checked formulation."
  ),
  productEconomics: synthesized(
    "COGS, retail price, and margin in this tab are the model's rough guess, generated independently from — and not reconciled with — the Manufacturing Intelligence tab's sourced estimate. The two numbers can disagree."
  ),
  financialProjections: synthesized(
    'Probability percentages and margins are generated to look like model output from a forecasting tool, but there is no statistical base-rate model or comparable-company dataset behind them.'
  ),
  marketSize: synthesized(
    'The model is instructed to hedge with "not independently verified" when it has no credible basis for the niche. Even when it states a specific figure instead, that figure is not sourced from a market research report.'
  ),
  opportunityScore: estimated(
    'Server-side formula',
    'Computed deterministically as a weighted blend of demand, revenue, market accessibility, consumer pain, virality, subscription, and manufacturing, recalculated server-side so the model cannot misreport its own math. The formula is exact; dimensions with a real provider use that real score, the rest are the model\'s own 0–10 judgment call — see the score breakdown for which is which.'
  ),
} satisfies Record<string, Provenance>

// ── Fields whose provenance depends on this specific memo's signal_metadata —
// real external data was available for some generations and not others. ──

export function demandProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.demand_verified) {
    return verified(
      'Keepa (Amazon)',
      "The demand SCORE shown is computed server-side from real Amazon sales-rank/search-volume data (lib/scoring.ts computeGroundedScore) — the model's own number is discarded whenever real data exists. Supplementary notes text is still model-written."
    )
  }
  return synthesized('No external demand data was available for this query — the score shown (if any) is the model\'s own qualitative judgment, not a number.')
}

export function viralityProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.virality_verified) {
    return estimated(
      'TikTok signal scrape',
      'Real TikTok content-volume/engagement signal was retrieved and inserted into the prompt as grounding context. The model still wrote the final score and notes text itself.'
    )
  }
  return synthesized('No external virality data was available for this query — score and notes are the model\'s own estimate.')
}

export function subscriptionProvenance(): Provenance {
  return synthesized(
    'Subscription-fit reasoning (repurchase cycle, retention) is the model\'s own judgment — no real repeat-purchase data source exists for a product that has not launched yet.'
  )
}

export function manufacturingScoreProvenance(): Provenance {
  return synthesized(
    "Formulation-complexity judgment by the model. For sourced cost/MOQ/supplier figures, see the Manufacturing Intelligence tab below."
  )
}

export function marketSaturationProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.market_verified) {
    return estimated(
      'Amazon seller-data signal',
      'Real competing-seller-count and saturation signal from Amazon listing data was inserted into the prompt as grounding context. The model still wrote the maturity/concentration/competitive-intensity text itself.'
    )
  }
  return synthesized('No external competitive-density data was available for this query — concentration, entry difficulty, and named dominant brands are the model\'s own recall.')
}

// "Biggest Competitor" — name and revenue are real when a competitor ASIN
// was found (Apify) and a targeted Keepa lookup on that exact ASIN
// succeeded (real price × real monthlySold). .gap stays model-written — a
// qualitative judgment, not a fetchable fact — though the model is now
// instructed to cite real Consumer Intelligence themes for it when available.
export function biggestCompetitorProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.competitor_revenue_verified) {
    return verified(
      'Apify + Keepa',
      "Name is the real #1 competitor by review count for this exact query (Apify). Revenue is a targeted Keepa lookup on that exact ASIN — real price × Keepa's own monthlySold estimate for that specific product, not a category average and not a guess. The gap sentence is still model-written."
    )
  }
  return synthesized("Competitor name, revenue, and gap are the model's best-guess recall from training knowledge — not pulled from Crunchbase, SEC filings, or any company database. (Real grounding requires a competitor ASIN to be found first; none was available for this query.)")
}

// ── Manufacturing Intelligence tab — a separate pipeline (/api/manufacturing)
// from the main memo body, with its own real-data path. ──

export function manufacturingTabProvenance(dataSource: string | undefined): Provenance {
  if (dataSource && dataSource !== 'ai_synthesis') {
    return verified(
      'Apify (live Alibaba supplier listings)',
      'Unit cost, MOQ, and supplier count are aggregated directly from real scraped Alibaba supplier listings — currency-converted, not generated by the model. Reflects listed asking prices, not a negotiated quote.'
    )
  }
  return synthesized('No live supplier listings were available — figures are the model\'s category-benchmark estimate.')
}

// ── Legacy field, no longer prompted for since the Phase 2 schema change. ──

export function legacyCompetitionProvenance(): Provenance {
  return unknown(
    'Carried over from an older memo schema (pre market_saturation). Provenance at the time it was generated cannot be reconstructed.'
  )
}

// ── False-precision guard: a bare model-generated percentage implies a
// calibrated statistical probability that doesn't exist here. Round to a
// 10-point band so the displayed number stops overstating its own
// precision, without inventing new bounds that aren't in the source value. ──

export function toConfidenceBand(pctStr: string | undefined): string {
  if (!pctStr) return pctStr ?? 'N/A'
  const match = pctStr.match(/(\d+(?:\.\d+)?)/)
  if (!match) return pctStr
  const n = parseFloat(match[1])
  const lo = Math.floor(n / 10) * 10
  const hi = lo + 10
  return `${lo}–${hi}%`
}

// ═══════════════════════════════════════════════════════════════
// EVIDENCE-FIRST LAYER — provenance for the raw signal/keyword data
// captured server-side (memo.signal_evidence / memo.keyword_intelligence).
// This data bypasses the LLM entirely, so classification is based on the
// underlying source's own nature (measured fact vs. provider-side estimate
// vs. a transparent formula over real inputs) — never "did the model use
// it correctly," since the model never touches this layer at all.
// ═══════════════════════════════════════════════════════════════

// ── No-fabrication zone: Search Volume, Revenue, Keyword Volume, and
// Competitor Counts. For these four specifically, there is no "fall back to
// the model's judgment" path — if the real source isn't there, the function
// returns `null` and the caller renders "No data available" literally,
// per explicit instruction. Every other provenance function in this file
// still degrades to `synthesized(...)` because a model-judgment fallback is
// fine for things that are inherently judgment calls (a thesis sentence, a
// risk severity); it is not fine for a number presented as a fact. ──

// "Monthly Search Volume" — real only via DataForSEO (m.keyword_intelligence).
// Neither Keepa nor Google Trends can measure this (see DemandSignal.search_volume
// comment in lib/signal-engine/types.ts) and no longer try to.
export function searchVolumeProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki || ki.top_buying.length === 0) return null
  return verified('DataForSEO', "Real monthly search volume for this query's top keyword, pulled directly from DataForSEO's keyword database.")
}

// "Search Growth %" — real via Google Trends' period-over-period computation
// on real (if relative) interest data. This is arithmetic on real numbers,
// not a guess, so it's allowed to exist even without DataForSEO.
export function searchGrowthProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.growth) return null
  return estimated(
    signals.growth.primarySource,
    `Computed from real period-over-period comparison of ${signals.growth.primarySource} time-series data — the direction and magnitude are real arithmetic on real data points, not a model guess.`
  )
}

// "90-Day Demand Momentum" — real via Keepa's own deltaPercent90_monthlySold
// field (CONFIRMED VIA LIVE CALL 2026-06-26). Same Estimated tier as
// monthlySold itself (unitsSoldProvenance below): a real platform-side
// estimate's real period-over-period delta, not a guess made up for this
// product, but not a directly-observed Amazon fact either.
export function demandMomentum90dProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (signals?.growth?.value.momentum_90d_pct == null) return null
  return estimated('Keepa', "Real 90-day percent change in Keepa's own monthlySold estimate for the category's top bestsellers — a more direct demand-momentum measurement than the BSR-ratio trend above, but still built on Keepa's modeled units-sold figure, not a directly observed fact.")
}

// "Amazon Referral Fee" / "FBA Pick & Pack Fee" — real Amazon fee-schedule
// data mirrored by Keepa per-product (CONFIRMED VIA LIVE CALL 2026-06-26:
// referralFeePercentage / fbaFees.pickAndPackFee on the Keepa product
// response). Verified, not Estimated: this is Amazon's own published fee
// schedule for the product's category/size tier, not a Keepa-side model.
export function realFeeDataProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const rev = signals?.revenue?.value
  if (rev?.avg_fba_pick_pack_fee === undefined && rev?.avg_referral_fee_pct === undefined) return null
  return verified('Keepa', "Amazon's own published referral-fee percentage and FBA pick-and-pack fee for this product's category/size tier, mirrored directly by Keepa — not a Keepa-side model and not the model's own margin guess.")
}

// "Estimated Monthly Units Sold" — real via Keepa's own monthlySold field.
export function unitsSoldProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.revenue?.value.est_monthly_units_sold) return null
  return estimated('Keepa', "Keepa's own monthlySold estimate for the category's top bestsellers — a real platform-side estimate, not a guess made up for this product.")
}

// "Estimated Monthly Revenue" / "Top Seller Revenue" / "Average Seller Revenue"
export function revenueEvidenceProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.revenue) return null
  return estimated(
    'Keepa',
    "Real price × Keepa's own estimated units-sold, for the category's top bestsellers overall — not your specific product idea. monthlySold is itself Keepa's modeled estimate, not a measured fact, so this number carries that uncertainty forward."
  )
}

// "Category Avg Rating" / "Category Avg Review Count" — unlike est_monthly_units_sold
// and revenue above (Keepa's own modeled estimates), rating and review count are
// directly observed Amazon facts that Keepa mirrors via &rating=1, not something
// Keepa models — Verified, not Estimated. Same category-bestseller scope caveat
// as the rest of this signal, called out explicitly in the detail text.
export function categoryReviewDataProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const rev = signals?.revenue?.value
  if (rev?.avg_rating === undefined && rev?.avg_review_count === undefined) return null
  return verified(
    'Keepa',
    "Real rating and review-count data, directly mirrored from Amazon (not modeled by Keepa), averaged across the category's top bestsellers — not specific to your exact product idea. Same category-wide scope as the revenue figures above."
  )
}

// "Competitor Count" / "Average Review Count" / "Market Concentration" — real
// only via a live Amazon search for this exact query (Apify's junglee/amazon-crawler
// actor — see providers/competition.ts). No fallback to market_saturation or any
// model-judgment substitute: a count either comes from counting real things,
// or it doesn't exist yet.
export function competitionEvidenceProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const hasRealCompetitorData = signals?.review_velocity?.value.meaningful_competitor_count !== undefined
  if (!hasRealCompetitorData) return null
  return verified(
    signals!.review_velocity!.primarySource,
    'Review counts, ratings, and brand names are pulled directly from real organic Amazon search results for this exact query — no estimation step, no LLM involvement.'
  )
}

// Market Accessibility Score is a separate, clearly-derived SCORE (not a raw
// count) built on top of the competition evidence above. Scores are allowed
// a model-judgment fallback because a score is inherently a judgment call;
// counts are not.
export function marketAccessibilityProvenance(signals?: AggregatedSignals | null): Provenance {
  const hasRealCompetitorData = signals?.review_velocity?.value.meaningful_competitor_count !== undefined
  if (!hasRealCompetitorData) return synthesized('Computed from model judgment only — no real competitor/review data was available to ground this score.')
  return estimated(
    'Server-side formula',
    "Computed deterministically from the real review-count and review-concentration data above. The arithmetic is exact and server-enforced; the thresholds that decide what counts as 'accessible' are a judgment call encoded in the formula, not derived from market research."
  )
}

export function keywordIntelligenceProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki) return null
  return verified(
    'DataForSEO',
    "Search volume, competition, and CPC are pulled directly from DataForSEO's keyword database. Growth % is computed here from their real monthly search-volume history, not requested as a pre-built metric — the bucketing into Top Buying / Opportunity / Long-Tail / Fast-Growing is a deterministic sort/filter over those real numbers, not a model judgment."
  )
}

// ── Keyword Intelligence Engine v2 (2026-06-26) — clusters, opportunity
// scores, seasonality, forecast, AI insights. Same "no fallback to model
// judgment for a number presented as fact" rule as the rest of this
// no-fabrication zone: every function below returns null rather than a
// guess when the underlying real field isn't present.

export function keywordClusterProvenance(): Provenance {
  return estimated(
    'Server-side rules',
    'Clusters are deterministic pattern-matches over the real DataForSEO keyword list (volume rank, word count, generic commerce/comparison/problem language, and real competitor brand names) — never an AI classification pass. A keyword can appear in more than one cluster.'
  )
}

export function keywordOpportunityScoreProvenance(): Provenance {
  return estimated(
    'Server-side formula',
    'Computed deterministically from real search volume (50% weight, log-scaled), real competition index (25%), and real keyword difficulty (25%). The arithmetic is exact; the weighting is a judgment call encoded in the formula, not derived from market research.'
  )
}

export function keywordClickConversionProvenance(): Provenance {
  return estimated(
    'Server-side formula',
    'Click potential assumes a 20% click-through rate for a top-3 organic ranking — a disclosed industry-typical benchmark, not measured for a listing that does not exist yet. Conversion potential additionally assumes a conversion rate tiered by search intent (2-10%). Treat both as directional, not a guarantee.'
  )
}

export function keywordAmazonPpcProvenance(): Provenance {
  return estimated(
    'Estimated — not Amazon Ads data',
    'This codebase has no live Amazon Ads API connection (the provider is an unimplemented stub). This range is derived from the keyword\'s real Google CPC, widened by real Amazon competitor density — a directional estimate, not a bid recommendation, and never presented as Amazon-sourced.'
  )
}

export function keywordSearchIntentProvenance(source?: 'dataforseo' | 'computed' | null): Provenance | null {
  if (!source) return null
  if (source === 'dataforseo') return verified('DataForSEO', "Search intent classification pulled directly from DataForSEO's own labeling for this keyword.")
  return estimated('Server-side rules', 'DataForSEO did not supply an intent classification for this keyword — this is a rule-based pattern match on generic commerce/navigational language, not a model guess and not provider-sourced.')
}

export function keywordSeasonalityProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki?.seasonality) return null
  return estimated(
    'Server-side formula',
    `Computed from real 12-month search-volume history for "${ki.seasonality.source_keyword}" (DataForSEO) using a coefficient-of-variation method — the same statistical method already used for category-level seasonality elsewhere in this report. The pattern thresholds are a judgment call; the underlying monthly volumes are real.`
  )
}

export function keywordForecastProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki?.forecast_12mo) return null
  return estimated(
    'Server-side formula',
    'A seasonal-naive statistical projection (same calendar month last year × the real recent YoY trend, capped to a sane range) over real DataForSEO history — not an AI forecast, not a guarantee. Requires a full real 12-month history; shown only when that exists.'
  )
}

export function keywordAiInsightsProvenance(): Provenance {
  return synthesized(
    'Narrative interpretation written by a separate, narrow AI pass over the real/computed keyword numbers above — it can describe and prioritize those numbers but cannot introduce a new metric, since none of its output is read back into any numeric field.'
  )
}

export function consumerIntelligenceProvenance(ci?: ConsumerIntelligenceReport | null): Provenance | null {
  if (!ci) return null
  return verified(
    'Apify (Amazon reviews)',
    `Every theme is a real, literal phrase pulled from ${ci.totalReviewsCollected} real customer reviews on ${(ci.productsAnalyzed ?? []).length} top competitor product(s) — no LLM summarization. Themes are found by deterministic phrase clustering (frequency + stemming, not free-form interpretation) and each one shows exactly how many of the analyzed reviews mentioned it. The review count next to every theme is the actual count, not an estimate.`
  )
}

// News items themselves (headline/date/source/url/category) come directly
// from openFDA/PubMed/GDELT with zero LLM involvement — Verified. The
// per-item "why it matters" caption and the overall summary ARE LLM-written
// (a separate Haiku call, lib/news-engine/explain.ts) but strictly grounded
// in the real items above — that distinction is called out in the detail
// text rather than hidden, same as biggestCompetitorProvenance's .gap caveat.
export function newsIntelligenceProvenance(ni?: NewsIntelligence | null): Provenance | null {
  if (!ni) return null
  if (!ni.hasRecentNews) {
    return verified(
      `${ni.providersUsed.length ? ni.providersUsed.join(', ') : 'openFDA, PubMed, GDELT'}`,
      'A real-time search across FDA recalls, PubMed, and live news search for this exact query found no items in the lookback window — this is a genuine "nothing found," not a failed search being hidden.'
    )
  }
  return verified(
    ni.providersUsed.join(', '),
    `Every headline, date, source, and link is pulled directly from ${ni.providersUsed.join('/')} — no LLM involvement in the items themselves. The "why it matters" caption on each item and the overall summary below are written by a separate, smaller AI pass given only these real items and instructed never to add or alter one — treat those two specifically as AI Interpretation, not verified fact, even though the items they're commenting on are real.`
  )
}

// "News Sentiment" — real GDELT mode=tonechart aggregate (CONFIRMED VIA LIVE
// CALL 2026-06-26). A real weighted average over real per-bin article
// counts across the whole query, not a per-item field and not AI-touched —
// best-effort, since GDELT's strict rate limit means this specific request
// sometimes returns nothing even when the headline items above succeeded.
export function newsSentimentProvenance(ni?: NewsIntelligence | null): Provenance | null {
  if (!ni?.sentiment) return null
  return verified(
    'GDELT',
    `Real weighted average over GDELT's tone histogram (${ni.sentiment.sample_size} real articles matching this query in the lookback window) — deterministic arithmetic over real per-bin counts, not a model judgment.`
  )
}

// Per-dimension provenance for the Opportunity Score breakdown
// (lib/scoring.ts computeGroundedScore) — one badge per dimension, distinct
// from the single overall opportunityScoreProvenance below.
export function scoreDimensionProvenance(d: ScoreDimension): Provenance {
  return d.source === 'verified'
    ? verified(d.sourceLabel, `This dimension's score (${d.rawScore}/10) is read directly from real provider data, not written by the model.`)
    : estimated(d.sourceLabel, `This dimension's score (${d.rawScore}/10) is the model's own judgment — ${d.sourceLabel.toLowerCase()}.`)
}

// Overall score provenance (2026-06-26 redesign): dimensions with no real
// basis no longer contribute any weight to the 0-100 score at all (see
// lib/scoring.ts header comment) — so groundedPct is now always 100 (at
// least one real dimension was found) or the score is flagged as
// insufficient evidence entirely. There is no longer a "partially real"
// blend to report; this caption now explains THAT rule, not a percentage.
export function opportunityScoreProvenance(groundedPct: number, insufficientEvidence = false): Provenance {
  if (insufficientEvidence) {
    return synthesized('No real provider data was found for any dimension of this query. The score shown is not a real verdict — treat it as "not enough evidence to assess," not as a SKIP recommendation.')
  }
  return estimated('Server-side formula', `Every dimension that contributes to this 0-100 score is backed by real provider data (Keepa/Apify/DataForSEO/TikTok) or a disclosed formula over real data — dimensions with no real basis (shown below) carry zero weight and never contribute a number, by design.`)
}

// Consistency-check flags (lib/consistency.ts) — a claim that was checked
// against real evidence and contradicted it, or had none to point to.
export function consistencyFlagProvenance(flag: ConsistencyFlag): Provenance {
  return unsupported(`${flag.claim}. ${flag.evidence}`)
}

// ── Evidence Coverage % ──────────────────────────────────────────────────────
// One number answering "how much of THIS report is real data vs AI
// judgment?" — every distinct field/dimension a memo can show, classified
// by its actual provenance for this specific generation. A field that came
// back "No data available" counts as ungrounded here, same as a field that
// is always AI-only by nature — both genuinely mean less of this report is
// backed by real evidence, which is the whole point of the metric. Verified
// and estimated both count as "grounded" (estimated = real data was given
// to the model as required context, even though the model wrote the final
// text) — synthesized and unknown count as "not grounded."

export interface EvidenceCoverage {
  pct:              number   // 0-100
  groundedCount:    number   // verified + estimated
  totalCount:       number
  verifiedCount:    number
  estimatedCount:   number
  synthesizedCount: number
  unknownCount:     number
}

export function computeEvidenceCoverage(m: MemoData): EvidenceCoverage {
  const sig = m.signal_metadata
  const se  = m.signal_evidence

  const fields: Provenance[] = [
    // Dimension scores
    demandProvenance(sig),
    viralityProvenance(sig),
    subscriptionProvenance(),
    manufacturingScoreProvenance(),
    marketSaturationProvenance(sig),
    // Narrative + static fields (everything in STATIC_PROVENANCE except the
    // opportunity score, which has its own real per-dimension breakdown via
    // lib/scoring.ts rather than the single static entry here)
    STATIC_PROVENANCE.executiveSummary,
    STATIC_PROVENANCE.marketThesis,
    STATIC_PROVENANCE.whyNow,
    STATIC_PROVENANCE.buildExplanation,
    STATIC_PROVENANCE.marketGaps,
    STATIC_PROVENANCE.brandOpportunities,
    STATIC_PROVENANCE.customerLanguage,
    STATIC_PROVENANCE.productFormula,
    STATIC_PROVENANCE.productEconomics,
    STATIC_PROVENANCE.financialProjections,
    STATIC_PROVENANCE.marketSize,
    biggestCompetitorProvenance(sig),
    // Evidence-first layer — counted as ungrounded (via the synthesized
    // fallback) when the real source wasn't available for this query,
    // exactly like every other field above.
    searchVolumeProvenance(m.keyword_intelligence) ?? synthesized('No real search-volume data (DataForSEO) was found for this query.'),
    searchGrowthProvenance(se) ?? synthesized('No real search-growth data (Keepa/Google Trends) was found for this query.'),
    unitsSoldProvenance(se) ?? synthesized('No real units-sold data (Keepa) was found for this query.'),
    revenueEvidenceProvenance(se) ?? synthesized('No real revenue data (Keepa) was found for this query.'),
    categoryReviewDataProvenance(se) ?? synthesized('No real rating/review data (Keepa) was found for this query.'),
    competitionEvidenceProvenance(se) ?? synthesized('No real competitor search data (Apify) was found for this query.'),
    marketAccessibilityProvenance(se),
    keywordIntelligenceProvenance(m.keyword_intelligence) ?? synthesized('No real keyword data (DataForSEO) was found for this query.'),
    consumerIntelligenceProvenance(m.consumer_intelligence) ?? synthesized('No real consumer review data (Apify) was found for this query.'),
    newsIntelligenceProvenance(m.news_intelligence) ?? unknown('This memo was generated before Real-Time News Intelligence existed, or the news pipeline did not run.'),
  ]

  const verifiedCount    = fields.filter(f => f.level === 'verified').length
  const estimatedCount   = fields.filter(f => f.level === 'estimated').length
  const synthesizedCount = fields.filter(f => f.level === 'synthesized').length
  const unknownCount     = fields.filter(f => f.level === 'unknown' || f.level === 'unsupported').length
  const groundedCount    = verifiedCount + estimatedCount
  const totalCount       = fields.length

  return {
    pct: totalCount > 0 ? Math.round((groundedCount / totalCount) * 100) : 0,
    groundedCount, totalCount, verifiedCount, estimatedCount, synthesizedCount, unknownCount,
  }
}
