// ═══════════════════════════════════════════════════════════════
// PROVENANCE — single source of truth for where every number, quote,
// and claim shown in a memo actually came from.
//
// Traced directly from the generation pipeline (app/api/generate/route.ts,
// lib/prompts/*, lib/categories/shared-prompts.ts, lib/signal-engine/*,
// lib/manufacturing-engine/*) — every classification below reflects what
// the code actually does, not what would be nice to claim.
//
// Four levels, matching how the data is actually produced:
//   verified    — pulled directly from a real external source, no LLM step
//   estimated   — real external data was retrieved AND given to the model
//                 as required grounding context, but the model still wrote
//                 the displayed score/notes text itself (compliance is a
//                 prompt instruction, not a server-enforced override)
//   synthesized — pure model output: pattern-matched from training
//                 knowledge, no external data involved at any stage
//   unknown     — provenance can't be determined (legacy/deprecated
//                 fields, failed-generation placeholders)
// ═══════════════════════════════════════════════════════════════

import type { MemoData, SignalMetadata } from '@/types/index'
import type { AggregatedSignals } from '@/lib/signal-engine/types'
import type { KeywordIntelligence } from '@/lib/keyword-engine/types'
import type { ConsumerIntelligenceReport } from '@/lib/consumer-intelligence'
import type { ScoreDimension } from '@/lib/scoring'
import type { ConsistencyFlag } from '@/lib/consistency'

// 'unsupported' is distinct from legacy 'unknown' — it means a specific,
// checkable claim was compared against real evidence (lib/consistency.ts)
// and contradicted or had no supporting data, not just "provenance unclear."
export type ProvenanceLevel = 'verified' | 'estimated' | 'synthesized' | 'unknown' | 'unsupported'

export interface Provenance {
  level:  ProvenanceLevel
  source: string   // short attribution, e.g. "Keepa (Amazon)"
  detail: string   // one- or two-sentence explanation, used as a tooltip
}

const verified    = (source: string, detail: string): Provenance => ({ level: 'verified', source, detail })
const estimated    = (source: string, detail: string): Provenance => ({ level: 'estimated', source, detail })
const synthesized = (detail: string): Provenance => ({ level: 'synthesized', source: 'Claude (AI synthesis)', detail })
const unsupported = (detail: string): Provenance => ({ level: 'unsupported', source: 'Consistency check', detail })
const unknown      = (detail: string): Provenance => ({ level: 'unknown', source: 'Unclassified', detail })

// ── Fields whose provenance is fixed regardless of which memo you're
// looking at — the generation pipeline never grounds these in real data. ──

export const STATIC_PROVENANCE = {
  executiveSummary: synthesized(
    'Narrative summary written by the model from the category prompt — not fact-checked against any external source.'
  ),
  marketThesis: synthesized(
    'Written in deliberately confident "VC deal memo" voice. Specific-sounding numbers inside this sentence are not independently sourced even when they look precise.'
  ),
  whyNow: synthesized(
    'The model is prompted to cite a concrete-sounding mechanism ("what changed in the last 12–24 months"). That mechanism is plausible pattern completion, not a sourced event — treat any percentage inside this text as unverified unless the Demand Momentum badge below it says otherwise.'
  ),
  buildExplanation: synthesized(
    "Model-written rationale summarizing its own dimension scores — not an independent review of the decision."
  ),
  marketGaps: synthesized(
    "Pattern-matched gaps from the model's training knowledge of the category — not derived from a live competitive scan or review-mining pipeline."
  ),
  brandOpportunities: synthesized(
    'Positioning angles generated by the model as creative suggestions — not tested messaging or validated against real ad performance.'
  ),
  customerLanguage: synthesized(
    'Frustrations, desires, fears, and ad phrases are still model-written, not pulled directly from review text. As of 2026-06-25 the model IS given real Consumer Intelligence themes (when available) and instructed to use them over inventing different ones — see the Consumer tab for the actual real-data themes this should be drawing from. Compliance is a prompt instruction, not server-enforced, so treat this section as informed-by-real-data rather than verified.'
  ),
  productFormula: synthesized(
    "Ingredient choices, doses, and evidence-tier stars are the model's clinical-literature pattern matching — treat as a starting hypothesis, not a citation-checked formulation."
  ),
  productEconomics: synthesized(
    "COGS, retail price, and margin in this tab are the model's rough guess, generated independently from — and not reconciled with — the Manufacturing Intelligence tab's sourced estimate. The two numbers can disagree."
  ),
  financialProjections: synthesized(
    'Probability percentages and margins are generated to look like model output from a forecasting tool, but there is no statistical base-rate model or comparable-company dataset behind them.'
  ),
  marketSize: synthesized(
    'The model is instructed to hedge with "not independently verified" when it has no credible basis for the niche. Even when it states a specific figure instead, that figure is not sourced from a market research report.'
  ),
  opportunityScore: estimated(
    'Server-side formula',
    'Computed deterministically as a weighted blend of demand, revenue, market accessibility, consumer pain, virality, subscription, and manufacturing, recalculated server-side so the model cannot misreport its own math. The formula is exact; dimensions with a real provider use that real score, the rest are the model\'s own 0–10 judgment call — see the score breakdown for which is which.'
  ),
} satisfies Record<string, Provenance>

// ── Fields whose provenance depends on this specific memo's signal_metadata —
// real external data was available for some generations and not others. ──

export function demandProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.demand_verified) {
    return estimated(
      'Keepa (Amazon)',
      'Real Amazon sales-rank / search-volume data was retrieved and inserted into the prompt as required grounding context, with an explicit instruction not to override it. The model still wrote the final score and notes text — compliance is a prompt instruction, not a server-enforced calculation.'
    )
  }
  return synthesized('No external demand data was available for this query — score and notes are the model\'s own estimate from training knowledge.')
}

export function viralityProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.virality_verified) {
    return estimated(
      'TikTok signal scrape',
      'Real TikTok content-volume/engagement signal was retrieved and inserted into the prompt as grounding context. The model still wrote the final score and notes text itself.'
    )
  }
  return synthesized('No external virality data was available for this query — score and notes are the model\'s own estimate.')
}

export function subscriptionProvenance(): Provenance {
  return synthesized(
    'Subscription-fit reasoning (repurchase cycle, retention) is the model\'s own judgment — no real repeat-purchase data source exists for a product that has not launched yet.'
  )
}

export function manufacturingScoreProvenance(): Provenance {
  return synthesized(
    "Formulation-complexity judgment by the model. For sourced cost/MOQ/supplier figures, see the Manufacturing Intelligence tab below."
  )
}

export function marketSaturationProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.market_verified) {
    return estimated(
      'Amazon seller-data signal',
      'Real competing-seller-count and saturation signal from Amazon listing data was inserted into the prompt as grounding context. The model still wrote the maturity/concentration/competitive-intensity text itself.'
    )
  }
  return synthesized('No external competitive-density data was available for this query — concentration, entry difficulty, and named dominant brands are the model\'s own recall.')
}

// "Biggest Competitor" — name and revenue are real when a competitor ASIN
// was found (Apify) and a targeted Keepa lookup on that exact ASIN
// succeeded (real price × real monthlySold). .gap stays model-written — a
// qualitative judgment, not a fetchable fact — though the model is now
// instructed to cite real Consumer Intelligence themes for it when available.
export function biggestCompetitorProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.competitor_revenue_verified) {
    return verified(
      'Apify + Keepa',
      "Name is the real #1 competitor by review count for this exact query (Apify). Revenue is a targeted Keepa lookup on that exact ASIN — real price × Keepa's own monthlySold estimate for that specific product, not a category average and not a guess. The gap sentence is still model-written."
    )
  }
  return synthesized("Competitor name, revenue, and gap are the model's best-guess recall from training knowledge — not pulled from Crunchbase, SEC filings, or any company database. (Real grounding requires a competitor ASIN to be found first; none was available for this query.)")
}

// ── Manufacturing Intelligence tab — a separate pipeline (/api/manufacturing)
// from the main memo body, with its own real-data path. ──

export function manufacturingTabProvenance(dataSource: string | undefined): Provenance {
  if (dataSource && dataSource !== 'ai_synthesis') {
    return verified(
      'Apify (live Alibaba supplier listings)',
      'Unit cost, MOQ, and supplier count are aggregated directly from real scraped Alibaba supplier listings — currency-converted, not generated by the model. Reflects listed asking prices, not a negotiated quote.'
    )
  }
  return synthesized('No live supplier listings were available — figures are the model\'s category-benchmark estimate.')
}

// ── Legacy field, no longer prompted for since the Phase 2 schema change. ──

export function legacyCompetitionProvenance(): Provenance {
  return unknown(
    'Carried over from an older memo schema (pre market_saturation). Provenance at the time it was generated cannot be reconstructed.'
  )
}

// ── False-precision guard: a bare model-generated percentage implies a
// calibrated statistical probability that doesn't exist here. Round to a
// 10-point band so the displayed number stops overstating its own
// precision, without inventing new bounds that aren't in the source value. ──

export function toConfidenceBand(pctStr: string | undefined): string {
  if (!pctStr) return pctStr ?? 'N/A'
  const match = pctStr.match(/(\d+(?:\.\d+)?)/)
  if (!match) return pctStr
  const n = parseFloat(match[1])
  const lo = Math.floor(n / 10) * 10
  const hi = lo + 10
  return `${lo}–${hi}%`
}

// ═══════════════════════════════════════════════════════════════
// EVIDENCE-FIRST LAYER — provenance for the raw signal/keyword data
// captured server-side (memo.signal_evidence / memo.keyword_intelligence).
// This data bypasses the LLM entirely, so classification is based on the
// underlying source's own nature (measured fact vs. provider-side estimate
// vs. a transparent formula over real inputs) — never "did the model use
// it correctly," since the model never touches this layer at all.
// ═══════════════════════════════════════════════════════════════

// ── No-fabrication zone: Search Volume, Revenue, Keyword Volume, and
// Competitor Counts. For these four specifically, there is no "fall back to
// the model's judgment" path — if the real source isn't there, the function
// returns `null` and the caller renders "No data available" literally,
// per explicit instruction. Every other provenance function in this file
// still degrades to `synthesized(...)` because a model-judgment fallback is
// fine for things that are inherently judgment calls (a thesis sentence, a
// risk severity); it is not fine for a number presented as a fact. ──

// "Monthly Search Volume" — real only via DataForSEO (m.keyword_intelligence).
// Neither Keepa nor Google Trends can measure this (see DemandSignal.search_volume
// comment in lib/signal-engine/types.ts) and no longer try to.
export function searchVolumeProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki || ki.top_buying.length === 0) return null
  return verified('DataForSEO', "Real monthly search volume for this query's top keyword, pulled directly from DataForSEO's keyword database.")
}

// "Search Growth %" — real via Google Trends' period-over-period computation
// on real (if relative) interest data. This is arithmetic on real numbers,
// not a guess, so it's allowed to exist even without DataForSEO.
export function searchGrowthProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.growth) return null
  return estimated(
    signals.growth.primarySource,
    `Computed from real period-over-period comparison of ${signals.growth.primarySource} time-series data — the direction and magnitude are real arithmetic on real data points, not a model guess.`
  )
}

// "Estimated Monthly Units Sold" — real via Keepa's own monthlySold field.
export function unitsSoldProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.revenue?.value.est_monthly_units_sold) return null
  return estimated('Keepa', "Keepa's own monthlySold estimate for the category's top bestsellers — a real platform-side estimate, not a guess made up for this product.")
}

// "Estimated Monthly Revenue" / "Top Seller Revenue" / "Average Seller Revenue"
export function revenueEvidenceProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.revenue) return null
  return estimated(
    'Keepa',
    "Real price × Keepa's own estimated units-sold, for the category's top bestsellers overall — not your specific product idea. monthlySold is itself Keepa's modeled estimate, not a measured fact, so this number carries that uncertainty forward."
  )
}

// "Category Avg Rating" / "Category Avg Review Count" — unlike est_monthly_units_sold
// and revenue above (Keepa's own modeled estimates), rating and review count are
// directly observed Amazon facts that Keepa mirrors via &rating=1, not something
// Keepa models — Verified, not Estimated. Same category-bestseller scope caveat
// as the rest of this signal, called out explicitly in the detail text.
export function categoryReviewDataProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const rev = signals?.revenue?.value
  if (rev?.avg_rating === undefined && rev?.avg_review_count === undefined) return null
  return verified(
    'Keepa',
    "Real rating and review-count data, directly mirrored from Amazon (not modeled by Keepa), averaged across the category's top bestsellers — not specific to your exact product idea. Same category-wide scope as the revenue figures above."
  )
}

// "Competitor Count" / "Average Review Count" / "Market Concentration" — real
// only via a live Amazon search for this exact query (Apify's junglee/amazon-crawler
// actor — see providers/competition.ts). No fallback to market_saturation or any
// model-judgment substitute: a count either comes from counting real things,
// or it doesn't exist yet.
export function competitionEvidenceProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const hasRealCompetitorData = signals?.review_velocity?.value.meaningful_competitor_count !== undefined
  if (!hasRealCompetitorData) return null
  return verified(
    signals!.review_velocity!.primarySource,
    'Review counts, ratings, and brand names are pulled directly from real organic Amazon search results for this exact query — no estimation step, no LLM involvement.'
  )
}

// Market Accessibility Score is a separate, clearly-derived SCORE (not a raw
// count) built on top of the competition evidence above. Scores are allowed
// a model-judgment fallback because a score is inherently a judgment call;
// counts are not.
export function marketAccessibilityProvenance(signals?: AggregatedSignals | null): Provenance {
  const hasRealCompetitorData = signals?.review_velocity?.value.meaningful_competitor_count !== undefined
  if (!hasRealCompetitorData) return synthesized('Computed from model judgment only — no real competitor/review data was available to ground this score.')
  return estimated(
    'Server-side formula',
    "Computed deterministically from the real review-count and review-concentration data above. The arithmetic is exact and server-enforced; the thresholds that decide what counts as 'accessible' are a judgment call encoded in the formula, not derived from market research."
  )
}

export function keywordIntelligenceProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki) return null
  return verified(
    'DataForSEO',
    "Search volume, competition, and CPC are pulled directly from DataForSEO's keyword database. Growth % is computed here from their real monthly search-volume history, not requested as a pre-built metric — the bucketing into Top Buying / Opportunity / Long-Tail / Fast-Growing is a deterministic sort/filter over those real numbers, not a model judgment."
  )
}

export function consumerIntelligenceProvenance(ci?: ConsumerIntelligenceReport | null): Provenance | null {
  if (!ci) return null
  return verified(
    'Apify (Amazon reviews)',
    `Every theme is a real, literal phrase pulled from ${ci.totalReviewsCollected} real customer reviews on ${ci.asinsAnalyzed.length} top competitor product(s) — no LLM summarization. Themes are found by deterministic phrase clustering (frequency + stemming, not free-form interpretation) and each one shows exactly how many of the analyzed reviews mentioned it. The review count next to every theme is the actual count, not an estimate.`
  )
}

// Per-dimension provenance for the Opportunity Score breakdown
// (lib/scoring.ts computeGroundedScore) — one badge per dimension, distinct
// from the single overall opportunityScoreProvenance below.
export function scoreDimensionProvenance(d: ScoreDimension): Provenance {
  return d.source === 'verified'
    ? verified(d.sourceLabel, `This dimension's score (${d.rawScore}/10) is read directly from real provider data, not written by the model.`)
    : estimated(d.sourceLabel, `This dimension's score (${d.rawScore}/10) is the model's own judgment — ${d.sourceLabel.toLowerCase()}.`)
}

// Overall score provenance — names what fraction of the score's weight is
// actually grounded, since the score itself is now a blend.
export function opportunityScoreProvenance(groundedPct: number): Provenance {
  if (groundedPct >= 50) {
    return estimated('Blended score', `${groundedPct}% of this score's weight comes from real provider data (Keepa/Apify/DataForSEO/TikTok); the rest is AI judgment, clearly marked below.`)
  }
  return synthesized(`Only ${groundedPct}% of this score's weight comes from real data — most of this number is AI judgment. Treat the BUILD_NOW/SKIP call with caution until more real signals are available.`)
}

// Consistency-check flags (lib/consistency.ts) — a claim that was checked
// against real evidence and contradicted it, or had none to point to.
export function consistencyFlagProvenance(flag: ConsistencyFlag): Provenance {
  return unsupported(`${flag.claim}. ${flag.evidence}`)
}

// ── Evidence Coverage % ──────────────────────────────────────────────────────
// One number answering "how much of THIS report is real data vs AI
// judgment?" — every distinct field/dimension a memo can show, classified
// by its actual provenance for this specific generation. A field that came
// back "No data available" counts as ungrounded here, same as a field that
// is always AI-only by nature — both genuinely mean less of this report is
// backed by real evidence, which is the whole point of the metric. Verified
// and estimated both count as "grounded" (estimated = real data was given
// to the model as required context, even though the model wrote the final
// text) — synthesized and unknown count as "not grounded."

export interface EvidenceCoverage {
  pct:              number   // 0-100
  groundedCount:    number   // verified + estimated
  totalCount:       number
  verifiedCount:    number
  estimatedCount:   number
  synthesizedCount: number
  unknownCount:     number
}

export function computeEvidenceCoverage(m: MemoData): EvidenceCoverage {
  const sig = m.signal_metadata
  const se  = m.signal_evidence

  const fields: Provenance[] = [
    // Dimension scores
    demandProvenance(sig),
    viralityProvenance(sig),
    subscriptionProvenance(),
    manufacturingScoreProvenance(),
    marketSaturationProvenance(sig),
    // Narrative + static fields (everything in STATIC_PROVENANCE except the
    // opportunity score, which has its own real per-dimension breakdown via
    // lib/scoring.ts rather than the single static entry here)
    STATIC_PROVENANCE.executiveSummary,
    STATIC_PROVENANCE.marketThesis,
    STATIC_PROVENANCE.whyNow,
    STATIC_PROVENANCE.buildExplanation,
    STATIC_PROVENANCE.marketGaps,
    STATIC_PROVENANCE.brandOpportunities,
    STATIC_PROVENANCE.customerLanguage,
    STATIC_PROVENANCE.productFormula,
    STATIC_PROVENANCE.productEconomics,
    STATIC_PROVENANCE.financialProjections,
    STATIC_PROVENANCE.marketSize,
    biggestCompetitorProvenance(sig),
    // Evidence-first layer — counted as ungrounded (via the synthesized
    // fallback) when the real source wasn't available for this query,
    // exactly like every other field above.
    searchVolumeProvenance(m.keyword_intelligence) ?? synthesized('No real search-volume data (DataForSEO) was found for this query.'),
    searchGrowthProvenance(se) ?? synthesized('No real search-growth data (Keepa/Google Trends) was found for this query.'),
    unitsSoldProvenance(se) ?? synthesized('No real units-sold data (Keepa) was found for this query.'),
    revenueEvidenceProvenance(se) ?? synthesized('No real revenue data (Keepa) was found for this query.'),
    categoryReviewDataProvenance(se) ?? synthesized('No real rating/review data (Keepa) was found for this query.'),
    competitionEvidenceProvenance(se) ?? synthesized('No real competitor search data (Apify) was found for this query.'),
    marketAccessibilityProvenance(se),
    keywordIntelligenceProvenance(m.keyword_intelligence) ?? synthesized('No real keyword data (DataForSEO) was found for this query.'),
    consumerIntelligenceProvenance(m.consumer_intelligence) ?? synthesized('No real consumer review data (Apify) was found for this query.'),
  ]

  const verifiedCount    = fields.filter(f => f.level === 'verified').length
  const estimatedCount   = fields.filter(f => f.level === 'estimated').length
  const synthesizedCount = fields.filter(f => f.level === 'synthesized').length
  const unknownCount     = fields.filter(f => f.level === 'unknown' || f.level === 'unsupported').length
  const groundedCount    = verifiedCount + estimatedCount
  const totalCount       = fields.length

  return {
    pct: totalCount > 0 ? Math.round((groundedCount / totalCount) * 100) : 0,
    groundedCount, totalCount, verifiedCount, estimatedCount, synthesizedCount, unknownCount,
  }
}
