// ═══════════════════════════════════════════════════════════════
// PROVENANCE — single source of truth for where every number, quote,
// and claim shown in a memo actually came from.
//
// Traced directly from the generation pipeline (app/api/generate/route.ts,
// lib/prompts/*, lib/categories/shared-prompts.ts, lib/signal-engine/*,
// lib/manufacturing-engine/*) — every classification below reflects what
// the code actually does, not what would be nice to claim.
//
// Four levels, matching how the data is actually produced:
//   verified    — pulled directly from a real external source, no LLM step
//   estimated   — real external data was retrieved AND given to the model
//                 as required grounding context, but the model still wrote
//                 the displayed score/notes text itself (compliance is a
//                 prompt instruction, not a server-enforced override)
//   synthesized — pure model output: pattern-matched from training
//                 knowledge, no external data involved at any stage
//   unknown     — provenance can't be determined (legacy/deprecated
//                 fields, failed-generation placeholders)
// ═══════════════════════════════════════════════════════════════

import type { MemoData, SignalMetadata } from '@/types/index'
import type { AggregatedSignals } from '@/lib/signal-engine/types'
import type { KeywordIntelligence } from '@/lib/keyword-engine/types'

export type ProvenanceLevel = 'verified' | 'estimated' | 'synthesized' | 'unknown'

export interface Provenance {
  level:  ProvenanceLevel
  source: string   // short attribution, e.g. "Keepa (Amazon)"
  detail: string   // one- or two-sentence explanation, used as a tooltip
}

const verified    = (source: string, detail: string): Provenance => ({ level: 'verified', source, detail })
const estimated    = (source: string, detail: string): Provenance => ({ level: 'estimated', source, detail })
const synthesized = (detail: string): Provenance => ({ level: 'synthesized', source: 'Claude (AI synthesis)', detail })
const unknown      = (detail: string): Provenance => ({ level: 'unknown', source: 'Unclassified', detail })

// ── Fields whose provenance is fixed regardless of which memo you're
// looking at — the generation pipeline never grounds these in real data. ──

export const STATIC_PROVENANCE = {
  executiveSummary: synthesized(
    'Narrative summary written by the model from the category prompt — not fact-checked against any external source.'
  ),
  marketThesis: synthesized(
    'Written in deliberately confident "VC deal memo" voice. Specific-sounding numbers inside this sentence are not independently sourced even when they look precise.'
  ),
  whyNow: synthesized(
    'The model is prompted to cite a concrete-sounding mechanism ("what changed in the last 12–24 months"). That mechanism is plausible pattern completion, not a sourced event — treat any percentage inside this text as unverified unless the Demand Momentum badge below it says otherwise.'
  ),
  buildExplanation: synthesized(
    "Model-written rationale summarizing its own dimension scores — not an independent review of the decision."
  ),
  marketGaps: synthesized(
    "Pattern-matched gaps from the model's training knowledge of the category — not derived from a live competitive scan or review-mining pipeline."
  ),
  brandOpportunities: synthesized(
    'Positioning angles generated by the model as creative suggestions — not tested messaging or validated against real ad performance.'
  ),
  customerLanguage: synthesized(
    'Frustrations, desires, fears, and ad phrases are model-generated to read like real customer quotes. They are not pulled from actual product reviews, surveys, or social posts — no review-scraping pipeline currently feeds this section, even though one exists elsewhere in this codebase and is not yet connected.'
  ),
  biggestCompetitor: synthesized(
    "Competitor name, revenue, and gap are the model's best-guess recall from training knowledge — not pulled from Crunchbase, SEC filings, or any company database."
  ),
  productFormula: synthesized(
    "Ingredient choices, doses, and evidence-tier stars are the model's clinical-literature pattern matching — treat as a starting hypothesis, not a citation-checked formulation."
  ),
  productEconomics: synthesized(
    "COGS, retail price, and margin in this tab are the model's rough guess, generated independently from — and not reconciled with — the Manufacturing Intelligence tab's sourced estimate. The two numbers can disagree."
  ),
  financialProjections: synthesized(
    'Probability percentages and margins are generated to look like model output from a forecasting tool, but there is no statistical base-rate model or comparable-company dataset behind them.'
  ),
  marketSize: synthesized(
    'The model is instructed to hedge with "not independently verified" when it has no credible basis for the niche. Even when it states a specific figure instead, that figure is not sourced from a market research report.'
  ),
  opportunityScore: estimated(
    'Server-side formula',
    'Computed deterministically as (demand + virality + subscription + manufacturing + defensibility) ÷ 50 × 100, recalculated server-side so the model cannot misreport its own math. The formula is exact; every input it operates on is the model\'s own 0–10 judgment call, not independently verified.'
  ),
} satisfies Record<string, Provenance>

// ── Fields whose provenance depends on this specific memo's signal_metadata —
// real external data was available for some generations and not others. ──

export function demandProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.demand_verified) {
    return estimated(
      'Keepa (Amazon)',
      'Real Amazon sales-rank / search-volume data was retrieved and inserted into the prompt as required grounding context, with an explicit instruction not to override it. The model still wrote the final score and notes text — compliance is a prompt instruction, not a server-enforced calculation.'
    )
  }
  return synthesized('No external demand data was available for this query — score and notes are the model\'s own estimate from training knowledge.')
}

export function viralityProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.virality_verified) {
    return estimated(
      'TikTok signal scrape',
      'Real TikTok content-volume/engagement signal was retrieved and inserted into the prompt as grounding context. The model still wrote the final score and notes text itself.'
    )
  }
  return synthesized('No external virality data was available for this query — score and notes are the model\'s own estimate.')
}

export function subscriptionProvenance(): Provenance {
  return synthesized(
    'Subscription-fit reasoning (repurchase cycle, retention) is the model\'s own judgment — no real repeat-purchase data source exists for a product that has not launched yet.'
  )
}

export function manufacturingScoreProvenance(): Provenance {
  return synthesized(
    "Formulation-complexity judgment by the model. For sourced cost/MOQ/supplier figures, see the Manufacturing Intelligence tab below."
  )
}

export function defensibilityProvenance(): Provenance {
  return synthesized('A subjective moat assessment — inherently a judgment call, not a verifiable fact.')
}

export function marketSaturationProvenance(sig?: SignalMetadata): Provenance {
  if (sig?.market_verified) {
    return estimated(
      'Amazon seller-data signal',
      'Real competing-seller-count and saturation signal from Amazon listing data was inserted into the prompt as grounding context. The model still wrote the maturity/concentration/competitive-intensity text itself.'
    )
  }
  return synthesized('No external competitive-density data was available for this query — concentration, entry difficulty, and named dominant brands are the model\'s own recall.')
}

// ── Manufacturing Intelligence tab — a separate pipeline (/api/manufacturing)
// from the main memo body, with its own real-data path. ──

export function manufacturingTabProvenance(dataSource: string | undefined): Provenance {
  if (dataSource && dataSource !== 'ai_synthesis') {
    return verified(
      'Apify (live Alibaba supplier listings)',
      'Unit cost, MOQ, and supplier count are aggregated directly from real scraped Alibaba supplier listings — currency-converted, not generated by the model. Reflects listed asking prices, not a negotiated quote.'
    )
  }
  return synthesized('No live supplier listings were available — figures are the model\'s category-benchmark estimate.')
}

// ── Legacy field, no longer prompted for since the Phase 2 schema change. ──

export function legacyCompetitionProvenance(): Provenance {
  return unknown(
    'Carried over from an older memo schema (pre market_saturation). Provenance at the time it was generated cannot be reconstructed.'
  )
}

// ── False-precision guard: a bare model-generated percentage implies a
// calibrated statistical probability that doesn't exist here. Round to a
// 10-point band so the displayed number stops overstating its own
// precision, without inventing new bounds that aren't in the source value. ──

export function toConfidenceBand(pctStr: string | undefined): string {
  if (!pctStr) return pctStr ?? 'N/A'
  const match = pctStr.match(/(\d+(?:\.\d+)?)/)
  if (!match) return pctStr
  const n = parseFloat(match[1])
  const lo = Math.floor(n / 10) * 10
  const hi = lo + 10
  return `${lo}–${hi}%`
}

// ═══════════════════════════════════════════════════════════════
// EVIDENCE-FIRST LAYER — provenance for the raw signal/keyword data
// captured server-side (memo.signal_evidence / memo.keyword_intelligence).
// This data bypasses the LLM entirely, so classification is based on the
// underlying source's own nature (measured fact vs. provider-side estimate
// vs. a transparent formula over real inputs) — never "did the model use
// it correctly," since the model never touches this layer at all.
// ═══════════════════════════════════════════════════════════════

// ── No-fabrication zone: Search Volume, Revenue, Keyword Volume, and
// Competitor Counts. For these four specifically, there is no "fall back to
// the model's judgment" path — if the real source isn't there, the function
// returns `null` and the caller renders "No data available" literally,
// per explicit instruction. Every other provenance function in this file
// still degrades to `synthesized(...)` because a model-judgment fallback is
// fine for things that are inherently judgment calls (a thesis sentence, a
// risk severity); it is not fine for a number presented as a fact. ──

// "Monthly Search Volume" — real only via DataForSEO (m.keyword_intelligence).
// Neither Keepa nor Google Trends can measure this (see DemandSignal.search_volume
// comment in lib/signal-engine/types.ts) and no longer try to.
export function searchVolumeProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki || ki.top_buying.length === 0) return null
  return verified('DataForSEO', "Real monthly search volume for this query's top keyword, pulled directly from DataForSEO's keyword database.")
}

// "Search Growth %" — real via Google Trends' period-over-period computation
// on real (if relative) interest data. This is arithmetic on real numbers,
// not a guess, so it's allowed to exist even without DataForSEO.
export function searchGrowthProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.growth) return null
  return estimated(
    signals.growth.primarySource,
    `Computed from real period-over-period comparison of ${signals.growth.primarySource} time-series data — the direction and magnitude are real arithmetic on real data points, not a model guess.`
  )
}

// "Estimated Monthly Units Sold" — real via Keepa's own monthlySold field.
export function unitsSoldProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.revenue?.value.est_monthly_units_sold) return null
  return estimated('Keepa', "Keepa's own monthlySold estimate for the category's top bestsellers — a real platform-side estimate, not a guess made up for this product.")
}

// "Estimated Monthly Revenue" / "Top Seller Revenue" / "Average Seller Revenue"
export function revenueEvidenceProvenance(signals?: AggregatedSignals | null): Provenance | null {
  if (!signals?.revenue) return null
  return estimated(
    'Keepa',
    "Real price × Keepa's own estimated units-sold, for the category's top bestsellers overall — not your specific product idea. monthlySold is itself Keepa's modeled estimate, not a measured fact, so this number carries that uncertainty forward."
  )
}

// "Category Avg Rating" / "Category Avg Review Count" — unlike est_monthly_units_sold
// and revenue above (Keepa's own modeled estimates), rating and review count are
// directly observed Amazon facts that Keepa mirrors via &rating=1, not something
// Keepa models — Verified, not Estimated. Same category-bestseller scope caveat
// as the rest of this signal, called out explicitly in the detail text.
export function categoryReviewDataProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const rev = signals?.revenue?.value
  if (rev?.avg_rating === undefined && rev?.avg_review_count === undefined) return null
  return verified(
    'Keepa',
    "Real rating and review-count data, directly mirrored from Amazon (not modeled by Keepa), averaged across the category's top bestsellers — not specific to your exact product idea. Same category-wide scope as the revenue figures above."
  )
}

// "Competitor Count" / "Average Review Count" / "Market Concentration" — real
// only via Rainforest's live organic search results for this exact query.
// No fallback to market_saturation or any model-judgment substitute: a count
// either comes from counting real things, or it doesn't exist yet.
export function competitionEvidenceProvenance(signals?: AggregatedSignals | null): Provenance | null {
  const hasRealCompetitorData = signals?.review_velocity?.value.meaningful_competitor_count !== undefined
  if (!hasRealCompetitorData) return null
  return verified(
    signals!.review_velocity!.primarySource,
    'Review counts, ratings, and brand names are pulled directly from real organic Amazon search results for this exact query — no estimation step, no LLM involvement.'
  )
}

// Market Accessibility Score is a separate, clearly-derived SCORE (not a raw
// count) built on top of the competition evidence above. Scores are allowed
// a model-judgment fallback because a score is inherently a judgment call;
// counts are not.
export function marketAccessibilityProvenance(signals?: AggregatedSignals | null): Provenance {
  const hasRealCompetitorData = signals?.review_velocity?.value.meaningful_competitor_count !== undefined
  if (!hasRealCompetitorData) return synthesized('Computed from model judgment only — no real competitor/review data was available to ground this score.')
  return estimated(
    'Server-side formula',
    "Computed deterministically from the real review-count and review-concentration data above. The arithmetic is exact and server-enforced; the thresholds that decide what counts as 'accessible' are a judgment call encoded in the formula, not derived from market research."
  )
}

export function keywordIntelligenceProvenance(ki?: KeywordIntelligence | null): Provenance | null {
  if (!ki) return null
  return verified(
    'DataForSEO',
    "Search volume, competition, and CPC are pulled directly from DataForSEO's keyword database. Growth % is computed here from their real monthly search-volume history, not requested as a pre-built metric — the bucketing into Top Buying / Opportunity / Long-Tail / Fast-Growing is a deterministic sort/filter over those real numbers, not a model judgment."
  )
}

export function memoProvenanceSummary(m: MemoData): { verifiedCount: number; estimatedCount: number; synthesizedCount: number } {
  const sig = m.signal_metadata
  const fields = [
    demandProvenance(sig),
    viralityProvenance(sig),
    subscriptionProvenance(),
    manufacturingScoreProvenance(),
    defensibilityProvenance(),
    marketSaturationProvenance(sig),
    ...Object.values(STATIC_PROVENANCE),
  ]
  return {
    verifiedCount:    fields.filter(f => f.level === 'verified').length,
    estimatedCount:   fields.filter(f => f.level === 'estimated').length,
    synthesizedCount: fields.filter(f => f.level === 'synthesized').length,
  }
}
