import type { EvidencePoint } from '../evidence/types'
import type { FounderProfile } from '../stage25/fit-layer'

// ── Stage 2: Investment Thesis ─────────────────────────────────────────────
// Generated by a single AI call grounded in Stage 1 signal data.
// Every evidence citation must reference a field that actually exists in
// Stage1Evidence — the generator prompt enforces this.

export interface QuickEconomicsCheck {
  price_point_estimate:   string    // e.g. "$32–$42 retail"
  min_capital_required:   number    // USD estimate to get to first 500 units
  margin_viable:          boolean   // can 50%+ GM be achieved at this price point?
  margin_note:            string    // brief explanation (max 1 sentence)
  launch_complexity:      'low' | 'medium' | 'high'
  complexity_drivers:     string[]  // e.g. ["regulatory", "formulation", "cold-chain"]
}

export interface CustomerPain {
  problem:          string   // what problem the product solves
  evidence_source:  string   // where this pain was observed (VOC, Reddit, reviews, etc.)
  pain_intensity:   'mild' | 'moderate' | 'severe'
  frequency:        'occasional' | 'recurring' | 'constant'
}

export interface InvestmentThesis {
  thesis_index:          number         // 1-based
  product_angle:         string         // specific product concept (not generic category)
  target_customer:       string         // specific persona, not "health-conscious consumers"
  differentiation:       string         // what makes this defensible against incumbents
  differentiation_source: string        // evidence backing this claim (must cite signal data)
  customer_pain:         CustomerPain
  supporting_evidence:   EvidencePoint<string>[]  // direct citations from Stage 1
  quick_economics_check: QuickEconomicsCheck
}

// Stored in DB — includes metadata and sourcing
export interface StoredThesis extends InvestmentThesis {
  id:               string
  market_signal_id: string
  user_id:          string
  created_at:       string
  ai_model_version: string
}

// ── Stage 2 generation request/response ───────────────────────────────────

export interface ThesisGenerationResult {
  theses:          InvestmentThesis[]
  generation_note: string   // any caveat the model noted (thin data, etc.)
  ai_model_version: string
}

// ── Stage 2.5: Founder Fit Annotation ─────────────────────────────────────
// Deterministic scoring — no AI. All logic is rule-based.

export type CapitalFitLevel   = 'sufficient' | 'tight' | 'insufficient'
export type ChannelFitLevel   = 'strong' | 'partial' | 'weak'
export type TimelineFitLevel  = 'feasible' | 'stretched' | 'infeasible'

export interface CapitalFit {
  level:             CapitalFitLevel
  capital_required:  number
  capital_available: number
  buffer_pct:        number   // (available - required) / required × 100
  note:              string
}

export interface ChannelFit {
  level:  ChannelFitLevel
  note:   string
}

export interface TimelineFit {
  level:  TimelineFitLevel
  note:   string
}

export interface FounderFitAnnotation {
  thesis_id:          string
  founder_profile_id: string
  fit_rank:           number          // 1–5 composite score (5 = best fit)
  capital_fit:        CapitalFit
  experience_gaps:    string[]
  channel_fit:        ChannelFit
  timeline_fit:       TimelineFit
  advantages:         string[]
  gaps:               string[]
}

export interface StoredFounderFitAnnotation extends FounderFitAnnotation {
  id:         string
  user_id:    string
  created_at: string
}

// Re-export FounderProfile for convenience
export type { FounderProfile }
