// ── Ingredient vocabulary — Roadmap "Dynamic Science Coverage" ──────────────
//
// docs/RD_DYNAMIC_SCIENCE_COVERAGE.md §3 step 1 (owner-approved 2026-07-28).
// A curated, human-reviewed, exact-match-only list of real dietary-
// supplement ingredient names — the kind of nomenclature that appears in
// NIH's Dietary Supplement Label Database (DSLD), the same real provider
// this codebase already integrates (lib/science-engine/dsld.ts) — hand-
// authored here as static data, not fetched from any live API. This file
// widens what lib/science-engine/tracked-ingredients.ts's
// matchTrackedIngredient() can recognize; it does NOT add a new matching
// mechanism (still simple, deterministic, whole-word exact match — no NLP,
// no fuzzy matching, no fabrication).
//
// Deliberately does NOT duplicate TRACKED_INGREDIENTS (berberine, creatine,
// magnesium) — those stay the priority benchmark list, matched first and
// separately by matchTrackedIngredient() before this file is even
// consulted (see that function's own comment).
//
// Shape mirrors lib/ingredient-registry/index.ts's `aliases` field: one
// canonical lowercase name plus real, known commercial/chemical/botanical
// name variants. A miss here degrades to today's exact behavior — honest
// absence, never a wrong match (R&D doc §4 Risks: "Vocabulary quality").
// Additions are one-line data changes, not a code change.

export interface VocabularyIngredient {
  canonical: string
  aliases:   string[]
}

export const INGREDIENT_VOCABULARY: VocabularyIngredient[] = [
  // ── Vitamins ────────────────────────────────────────────────────────────
  { canonical: 'vitamin a',         aliases: ['retinol', 'retinyl palmitate', 'beta-carotene'] },
  { canonical: 'vitamin c',         aliases: ['ascorbic acid', 'ascorbate', 'calcium ascorbate'] },
  { canonical: 'vitamin d3',        aliases: ['cholecalciferol'] },
  { canonical: 'vitamin d2',        aliases: ['ergocalciferol'] },
  { canonical: 'vitamin e',         aliases: ['tocopherol', 'alpha-tocopherol', 'mixed tocopherols'] },
  { canonical: 'vitamin k1',        aliases: ['phylloquinone'] },
  { canonical: 'vitamin k2',        aliases: ['menaquinone', 'mk-7', 'mk-4'] },
  { canonical: 'thiamine',          aliases: ['vitamin b1', 'thiamin', 'benfotiamine'] },
  { canonical: 'riboflavin',        aliases: ['vitamin b2'] },
  { canonical: 'niacin',            aliases: ['vitamin b3', 'nicotinic acid', 'niacinamide', 'nicotinamide'] },
  { canonical: 'pantothenic acid',  aliases: ['vitamin b5', 'calcium pantothenate'] },
  { canonical: 'pyridoxine',        aliases: ['vitamin b6', 'pyridoxal-5-phosphate'] },
  { canonical: 'biotin',            aliases: ['vitamin b7', 'vitamin h'] },
  { canonical: 'folate',            aliases: ['folic acid', 'vitamin b9', 'methylfolate', 'l-methylfolate'] },
  { canonical: 'cobalamin',         aliases: ['vitamin b12', 'methylcobalamin', 'cyanocobalamin', 'hydroxocobalamin'] },
  { canonical: 'choline',           aliases: ['choline bitartrate', 'phosphatidylcholine'] },

  // ── Minerals (excluding magnesium — already a TRACKED_INGREDIENT) ───────
  { canonical: 'calcium',           aliases: ['calcium carbonate', 'calcium citrate'] },
  { canonical: 'zinc',              aliases: ['zinc picolinate', 'zinc gluconate', 'zinc citrate'] },
  { canonical: 'iron',              aliases: ['ferrous sulfate', 'ferrous bisglycinate', 'ferric pyrophosphate'] },
  { canonical: 'potassium',         aliases: ['potassium citrate', 'potassium chloride'] },
  { canonical: 'selenium',          aliases: ['selenomethionine', 'sodium selenite'] },
  { canonical: 'iodine',            aliases: ['potassium iodide', 'kelp iodine'] },
  { canonical: 'chromium',          aliases: ['chromium picolinate', 'chromium polynicotinate'] },
  { canonical: 'copper',            aliases: ['copper gluconate', 'copper bisglycinate'] },
  { canonical: 'manganese',         aliases: ['manganese gluconate'] },
  { canonical: 'molybdenum',        aliases: [] },
  { canonical: 'boron',             aliases: ['boron citrate'] },
  { canonical: 'phosphorus',        aliases: [] },

  // ── Amino acids / derivatives ────────────────────────────────────────────
  { canonical: 'l-theanine',        aliases: ['theanine', 'suntheanine'] },
  { canonical: 'l-carnitine',       aliases: ['carnitine', 'acetyl-l-carnitine', 'alcar', 'l-carnitine tartrate'] },
  { canonical: 'l-arginine',        aliases: ['arginine', 'arginine alpha-ketoglutarate'] },
  { canonical: 'l-citrulline',      aliases: ['citrulline', 'citrulline malate'] },
  { canonical: 'l-glutamine',       aliases: ['glutamine'] },
  { canonical: 'l-lysine',          aliases: ['lysine'] },
  { canonical: 'l-tyrosine',        aliases: ['tyrosine', 'n-acetyl l-tyrosine'] },
  { canonical: 'l-tryptophan',      aliases: ['tryptophan'] },
  { canonical: 'taurine',           aliases: [] },
  { canonical: 'glycine',           aliases: [] },
  { canonical: 'leucine',           aliases: ['l-leucine'] },
  { canonical: 'isoleucine',        aliases: ['l-isoleucine'] },
  { canonical: 'valine',            aliases: ['l-valine'] },
  { canonical: 'branched chain amino acids', aliases: ['bcaa', 'bcaas'] },
  { canonical: 'gaba',              aliases: ['gamma-aminobutyric acid'] },
  { canonical: '5-htp',             aliases: ['5-hydroxytryptophan'] },
  { canonical: 'n-acetylcysteine',  aliases: ['nac'] },
  { canonical: 'sam-e',             aliases: ['s-adenosylmethionine'] },
  { canonical: 'betaine anhydrous', aliases: ['trimethylglycine', 'tmg'] },
  { canonical: 'agmatine sulfate',  aliases: ['agmatine'] },
  { canonical: 'beta-alanine',      aliases: [] },
  { canonical: 'hmb',               aliases: ['beta-hydroxy beta-methylbutyrate', 'calcium hmb'] },

  // ── Nootropics / cognitive ────────────────────────────────────────────────
  { canonical: 'phosphatidylserine', aliases: [] },
  { canonical: 'alpha-gpc',          aliases: ['alpha-glycerophosphocholine', 'choline alfoscerate'] },
  { canonical: 'huperzine a',        aliases: [] },
  { canonical: 'vinpocetine',        aliases: [] },
  { canonical: 'bacopa monnieri',    aliases: ['brahmi'] },
  { canonical: 'lions mane mushroom', aliases: ['hericium erinaceus'] },
  { canonical: 'dmae',               aliases: ['dimethylaminoethanol'] },
  { canonical: 'noopept',            aliases: [] },
  { canonical: 'citicoline',         aliases: ['cdp-choline'] },

  // ── Herbal / botanical ────────────────────────────────────────────────────
  { canonical: 'ashwagandha',        aliases: ['withania somnifera', 'indian ginseng', 'ksm-66', 'sensoril'] },
  { canonical: 'rhodiola rosea',     aliases: ['rhodiola', 'golden root'] },
  { canonical: 'panax ginseng',      aliases: ['korean ginseng', 'asian ginseng', 'red ginseng'] },
  { canonical: 'american ginseng',   aliases: ['panax quinquefolius'] },
  { canonical: 'turmeric',           aliases: ['curcuma longa'] },
  { canonical: 'curcumin',           aliases: ['curcuminoids'] },
  { canonical: 'ginger',             aliases: ['zingiber officinale', 'ginger root'] },
  { canonical: 'garlic',             aliases: ['allicin', 'aged garlic extract'] },
  { canonical: 'milk thistle',       aliases: ['silymarin', 'silybum marianum'] },
  { canonical: 'echinacea',          aliases: ['echinacea purpurea'] },
  { canonical: 'elderberry',         aliases: ['sambucus nigra', 'sambucus'] },
  { canonical: 'st johns wort',      aliases: ['hypericum perforatum'] },
  { canonical: 'valerian root',      aliases: ['valeriana officinalis'] },
  { canonical: 'chamomile',          aliases: ['matricaria chamomilla', 'german chamomile'] },
  { canonical: 'passionflower',      aliases: ['passiflora incarnata'] },
  { canonical: 'lemon balm',         aliases: ['melissa officinalis'] },
  { canonical: 'holy basil',         aliases: ['tulsi', 'ocimum sanctum'] },
  { canonical: 'ginkgo biloba',      aliases: ['ginkgo'] },
  { canonical: 'saw palmetto',       aliases: ['serenoa repens'] },
  { canonical: 'maca root',          aliases: ['lepidium meyenii', 'maca'] },
  { canonical: 'tribulus terrestris', aliases: ['tribulus'] },
  { canonical: 'fenugreek',          aliases: ['trigonella foenum-graecum'] },
  { canonical: 'green tea extract',  aliases: ['egcg', 'epigallocatechin gallate'] },
  { canonical: 'green coffee bean extract', aliases: ['chlorogenic acid'] },
  { canonical: 'garcinia cambogia',  aliases: ['hydroxycitric acid'] },
  { canonical: 'forskolin',          aliases: ['coleus forskohlii'] },
  { canonical: 'black cohosh',       aliases: ['actaea racemosa'] },
  { canonical: 'dong quai',          aliases: ['angelica sinensis'] },
  { canonical: 'chasteberry',        aliases: ['vitex agnus-castus', 'vitex'] },
  { canonical: 'horny goat weed',    aliases: ['epimedium', 'icariin'] },
  { canonical: 'yohimbe',            aliases: ['yohimbine', 'pausinystalia yohimbe'] },
  { canonical: 'tongkat ali',        aliases: ['eurycoma longifolia', 'longjack'] },
  { canonical: 'fadogia agrestis',   aliases: [] },
  { canonical: 'schisandra',         aliases: ['schisandra chinensis'] },
  { canonical: 'astragalus',         aliases: ['astragalus membranaceus'] },
  { canonical: 'cordyceps',          aliases: ['cordyceps sinensis', 'cordyceps militaris'] },
  { canonical: 'reishi mushroom',    aliases: ['ganoderma lucidum'] },
  { canonical: 'chaga mushroom',     aliases: ['inonotus obliquus'] },
  { canonical: 'moringa',            aliases: ['moringa oleifera'] },
  { canonical: 'spirulina',          aliases: ['arthrospira platensis'] },
  { canonical: 'chlorella',          aliases: [] },
  { canonical: 'aloe vera',          aliases: [] },
  { canonical: 'cranberry extract',  aliases: ['vaccinium macrocarpon'] },
  { canonical: 'pomegranate extract', aliases: ['punica granatum'] },
  { canonical: 'resveratrol',        aliases: ['trans-resveratrol'] },
  { canonical: 'quercetin',          aliases: [] },
  { canonical: 'bilberry extract',   aliases: ['vaccinium myrtillus'] },
  { canonical: 'grape seed extract', aliases: ['vitis vinifera'] },
  { canonical: 'pine bark extract',  aliases: ['pycnogenol'] },
  { canonical: 'boswellia',          aliases: ['boswellia serrata', 'indian frankincense'] },
  { canonical: 'devils claw',        aliases: ['harpagophytum procumbens'] },
  { canonical: 'white willow bark',  aliases: ['salix alba'] },
  { canonical: 'cats claw',          aliases: ['uncaria tomentosa'] },
  { canonical: 'olive leaf extract', aliases: ['oleuropein'] },
  { canonical: 'oregano oil',        aliases: ['origanum vulgare'] },
  { canonical: 'black seed oil',     aliases: ['nigella sativa', 'black cumin seed oil'] },
  { canonical: 'triphala',           aliases: [] },
  { canonical: 'licorice root',      aliases: ['glycyrrhiza glabra', 'deglycyrrhizinated licorice'] },
  { canonical: 'slippery elm',       aliases: ['ulmus rubra'] },
  { canonical: 'marshmallow root',   aliases: ['althaea officinalis'] },
  { canonical: 'psyllium husk',      aliases: ['plantago ovata'] },
  { canonical: 'senna',              aliases: ['senna alexandrina'] },
  { canonical: 'cascara sagrada',    aliases: [] },
  { canonical: 'butterbur',          aliases: ['petasites hybridus'] },
  { canonical: 'feverfew',           aliases: ['tanacetum parthenium'] },
  { canonical: 'kava',               aliases: ['kava kava', 'piper methysticum'] },
  { canonical: 'hops extract',       aliases: ['humulus lupulus'] },
  { canonical: 'skullcap',           aliases: ['scutellaria lateriflora'] },
  { canonical: 'motherwort',         aliases: ['leonurus cardiaca'] },
  { canonical: 'mucuna pruriens',    aliases: ['velvet bean'] },
  { canonical: 'shilajit',           aliases: ['mumijo'] },
  { canonical: 'pygeum africanum',   aliases: [] },
  { canonical: 'stinging nettle',    aliases: ['urtica dioica', 'nettle root'] },
  { canonical: 'dandelion root',     aliases: ['taraxacum officinale'] },
  { canonical: 'artichoke extract',  aliases: ['cynara scolymus'] },
  { canonical: 'hibiscus extract',   aliases: ['hibiscus sabdariffa'] },
  { canonical: 'wild yam',           aliases: ['dioscorea villosa'] },
  { canonical: 'red clover',         aliases: ['trifolium pratense'] },
  { canonical: 'evening primrose oil', aliases: ['oenothera biennis'] },
  { canonical: 'black pepper extract', aliases: ['piperine', 'bioperine'] },
  { canonical: 'cinnamon extract',   aliases: ['ceylon cinnamon', 'cinnamomum verum'] },

  // ── Other common branded-compound generics ───────────────────────────────
  { canonical: 'coenzyme q10',       aliases: ['coq10', 'ubiquinone', 'ubiquinol'] },
  { canonical: 'fish oil',           aliases: ['omega-3', 'fish oil concentrate'] },
  { canonical: 'krill oil',          aliases: ['euphausia superba'] },
  { canonical: 'alpha lipoic acid',  aliases: ['thioctic acid'] },
  { canonical: 'melatonin',          aliases: [] },
  { canonical: 'glucosamine',        aliases: ['glucosamine sulfate', 'glucosamine hcl'] },
  { canonical: 'chondroitin',        aliases: ['chondroitin sulfate'] },
  { canonical: 'msm',                aliases: ['methylsulfonylmethane'] },
  { canonical: 'collagen peptides',  aliases: ['hydrolyzed collagen', 'collagen hydrolysate'] },
  { canonical: 'hyaluronic acid',    aliases: ['sodium hyaluronate'] },
  { canonical: 'probiotics',         aliases: ['lactobacillus acidophilus', 'bifidobacterium lactis'] },
  { canonical: 'inulin',             aliases: ['chicory root fiber'] },
  { canonical: 'bromelain',          aliases: [] },
  { canonical: 'papain',             aliases: [] },
  { canonical: 'caffeine anhydrous', aliases: ['caffeine'] },
  { canonical: 'theobromine',        aliases: [] },
  { canonical: 'guarana',            aliases: ['paullinia cupana'] },
  { canonical: 'yerba mate',         aliases: ['ilex paraguariensis'] },
  { canonical: 'dhea',               aliases: ['dehydroepiandrosterone'] },
  { canonical: 'pregnenolone',       aliases: [] },
  { canonical: 'conjugated linoleic acid', aliases: ['cla'] },
  { canonical: 'raspberry ketones',  aliases: [] },
  { canonical: 'chitosan',           aliases: [] },
  { canonical: 'white kidney bean extract', aliases: ['phaseolus vulgaris'] },
  { canonical: 'apple cider vinegar', aliases: [] },
  { canonical: 'beta-glucan',        aliases: ['oat beta-glucan'] },
  { canonical: 'lutein',             aliases: ['marigold extract'] },
  { canonical: 'zeaxanthin',         aliases: [] },
  { canonical: 'astaxanthin',        aliases: ['haematococcus pluvialis'] },
  { canonical: 'lycopene',           aliases: [] },
  { canonical: 'nattokinase',        aliases: [] },
  { canonical: 'serrapeptase',       aliases: [] },
  { canonical: 'betaine hcl',        aliases: ['betaine hydrochloride'] },
  { canonical: 'apigenin',           aliases: [] },
  { canonical: 'chrysin',            aliases: [] },
  { canonical: 'dim',                aliases: ['diindolylmethane'] },
  { canonical: 'indole-3-carbinol',  aliases: ['i3c'] },
  { canonical: 'pterostilbene',      aliases: [] },
  { canonical: 'nmn',                aliases: ['nicotinamide mononucleotide'] },
  { canonical: 'nicotinamide riboside', aliases: ['nr'] },
  { canonical: 'pqq',                aliases: ['pyrroloquinoline quinone'] },
  { canonical: 'glutathione',        aliases: ['l-glutathione', 'reduced glutathione'] },
]
